### ISSUE TITLE
SDL2.dll MISSING!!

### ISSUE THREAD

**Issue by gamingaddictionz03** [MarcuzD/HorizonM#11]
when i put in my 3ds ip address in the HorizonM applization on my pc, it says the SDL2.dll is missing from my computer

**Comment by FateForWindows** [comment]
Make sure to move HorizonM.exe and HorizonM.elf to the HorizonScreen folder, if you need to, follow this tutorial:
https://www.youtube.com/watch?v=oLfalhFEixA

**Comment by FateForWindows** [comment]
Due to this issue being of human error, it should be closed (it's next to the comment button).

**Comment by MarcuzD** [comment]
READ THE [README!](https://github.com/MarcuzD/HorizonM/blob/master/HorizonScreen/README.md)
