### ISSUE TITLE
FRAME RATES!!

### ISSUE THREAD

**Issue by gamingaddictionz03** [MarcuzD/HorizonM#13]
how do i increase my framerates during the recording?

**Comment by FateForWindows** [comment]
You can't and that's not a bug, especially on O3DS, and there might be minor tweaks but it probably won't go above 5 frames. This issue should be closed.

**Comment by MarcuzD** [comment]
ask Nintendo to make a new new new newnewnewnewnewnewnewnew3DSXXXXXXXXXXXL with a faster CPU and a better networking card, and that would increate the frame rates a bit

I'll release updates which might increate the output framerate, but there's a limit of what the 3DS hardware can put out
