### ISSUE TITLE
HzLoad splash screen

### ISSUE THREAD

**Issue by Jolty95** [MarcuzD/HorizonM#2]
Hi there!
HzLoad (and highmem I guest) is using the Ninty 3DS Splash Screen.
Are you going to use the "homebrew" splash screen instead? :)

**Comment by MarcuzD** [comment]
herp-derp >.<
thanks for pointing out! will fix in a few recent commits!

**Comment by Jolty95** [comment]
NP :) Btw, can't compile client for PC in Windows or Linux. Windows doesn't have poll.h and Linux is getting undefined references.

**Comment by MarcuzD** [comment]
I was told that Windows has similarities to UNIX sockets, but I have never learned how to use WINAPI outside C#, so it'll take a while while I add support for it (unless someone makes a pull request)

**Comment by Jolty95** [comment]
I'm getting in linux an error in line 284:71 of main.cpp in function `int main(int, char**)` and an error `error: 'SDL_CreateRGBSurfaceWithFormat' was not declared in this scope` 
`img[0] = SDL_CreateRGBSurfaceWithFormat(0, 240, 400, 32, pixfmt[0])); ` 
Makefile line 139

Anyway, since this issue was opened to notify you about the splash screen, I'll close it now :) (and If you know how I can solve this problem, I'll thanks you too :P)

**Comment by MarcuzD** [comment]
Please don't close this issue or I'll forget to change the banner :stuck_out_tongue:

As for the SDL2 2.0.5 dependency, it looks like I haven't emphasized it enough in the README :frowning_face:

**Comment by Jolty95** [comment]
Sorry about closing it >.< 
And about the 2.0.5 at least for me I cannot find any precompiled version anywhere that's why I suggested that :) (btw, small typo mistake in install SDL2 in readme :P)

**Comment by MarcuzD** [comment]
there is no typo >_> it clearly states that it needs SDL2 2.0.5 or above

**Comment by Jolty95** [comment]
@MarcuzD  I mean this ` instlall libSDL2-dev 2.0.5+ ` instead of install :P

**Comment by MarcuzD** [comment]
ah, okay :P thanks, fixed!
